version: '3.8'

services:
  web:
    build: .
    container_name: techblood-agency
    image: techblood-agency
    ports:
      - "80:80"  # Porta pública (80) : Porta interna (8080)
    restart: always
    environment:
      - FLASK_ENV=production
    command: gunicorn -b 0.0.0.0:8080 app:app
